version: '3.5'
services:
  mysql_m1:
    image: mysql:8.0.14
    container_name: mysql-m1
    ports:
      - '3311:3306'
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - mysql-m1-volume:/var/lib/mysql
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
      MYSQL_DATABASE: 'todolist'
      MYSQL_ROOT_HOST: '%'
#  mysql_s1:
#    image: mysql:8.0.14
#    container_name: mysql-s1
#    ports:
#      - '4311:3306'
#    deploy:
#      resources:
#        limits:
#          memory: 256M
#    volumes:
#      - mysql-s1-volume:/var/lib/mysql
#    networks:
#      - back-tier
#    environment:
#      MYSQL_ROOT_PASSWORD: '111111'
#      MYSQL_DATABASE: 'todolist'
#      MYSQL_ROOT_HOST: '%'

  mysql_m2:
    image: mysql:8.0.14
    container_name: mysql-m2
    ports:
      - '3312:3306'
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - mysql-m2-volume:/var/lib/mysql
    networks:
      - back-tier
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
      MYSQL_DATABASE: 'todolist'
      MYSQL_ROOT_HOST: '%'
#  mysql_s2:
#    image: mysql:8.0.14
#    container_name: mysql-s2
#    ports:
#      - '4312:3306'
#    deploy:
#      resources:
#        limits:
#          memory: 256M
#    volumes:
#      - mysql-s2-volume:/var/lib/mysql
#    networks:
#      - back-tier
#    environment:
#      MYSQL_ROOT_PASSWORD: '111111'
#      MYSQL_DATABASE: 'todolist'
#      MYSQL_ROOT_HOST: '%'

  rabbitmq_m1:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq-m1
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 15680:15672
      - 5680:5672
    networks:
      - back-tier
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1234qwer
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: 1234qwer

volumes:
  mysql-m1-volume:
  mysql-s1-volume:
  mysql-m2-volume:
  mysql-s2-volume:

networks:
  back-tier:
    driver: bridge
