SERVER_PORT: 8080

# MYSQL
MYSQL_URL: jdbc:mysql://localhost:3307/prediction_expert?serverTimezone=UTC
MYSQL_USERNAME: root
MYSQL_PASSWORD: '111111'
MYSQL_MAX_POOL_SIZE: 100
MYSQL_MINI_IDLE: 10
MYSQL_IDLE_TIMEOUT: 600000
MYSQL_CONNECTION_TIMEOUT: 30000
MYSQL_MAX_LIFE_TIME: 1800000
MYSQL_VALIDATION_TIME: 5000

# RABBITMQ
RABBITMQ_HOST: 127.0.0.1
RABBITMQ_USER: user
RABBITMQ_PASSWORD: 123123
RABBITMQ_PORT: 5672
RABBITMQ_VIRTUAL_HOST: /
RABBITMQ_CONCURRENCY: 2
RABBITMQ_MAX_CONCURRENCY: 10
RABBITMQ_SHUTDOWN_TIMEOUT: 120000

#URL
ATHENA_URL: http://127.0.0.1:8800
HESTIA_URL: http://127.0.0.1:9000
HERACLES_URL: http://127.0.0.1:8200
ARES_URL: http://localhost:8888
METIS_URL: http://127.0.0.1:9300

# Redis Cluster
REDIS_NODES: 192.168.20.188:7000,192.168.20.188:7001,192.168.20.188:7002,192.168.20.188:7003,192.168.20.188:7004,192.168.20.188:7005
REDIS_PASSWORD: zCTkps5mfskXADtU
REDIS_POOL_MAX_ACTIVE: 100
REDIS_POOL_MAX_WAIT: 100
REDIS_POOL_MAX_IDLE: 10
REDIS_POOL_MIN_IDLE: 5