server:
  port: ${SERVER_PORT}
  tomcat:
    protocol: org.apache.coyote.http11.Http11Nio2Protocol

spring:
  profiles:
    active: local
  application:
    name: apollo
  flyway:
    out-of-order: true
  datasource:
    apollo:
      hikari:
        jdbcUrl: ${MYSQL_URL}
        driverClassName: com.mysql.cj.jdbc.Driver
        pool-name: apollo-jdbc-pool
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        maximumPoolSize: ${MYSQL_MAX_POOL_SIZE}
        minimumIdle: ${MYSQL_MINI_IDLE}
        idleTimeout: ${MYSQL_IDLE_TIMEOUT}
        connectionTimeout: ${MYSQL_CONNECTION_TIMEOUT}
        maxLifetime: ${MYSQL_MAX_LIFE_TIME}
        validationTimeout: ${MYSQL_VALIDATION_TIME}
        connectionTestQuery: SELECT 1 FROM DUAL
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  rabbitmq:
    addresses: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
    port: ${RABBITMQ_PORT}
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: manual
        concurrency: ${RABBITMQ_CONCURRENCY}
        max-concurrency: ${RABBITMQ_MAX_CONCURRENCY}
        shutdown:
          timeout: ${RABBITMQ_SHUTDOWN_TIMEOUT}
        retry:
          enabled: false
    publisher-confirms: true
    publisher-returns: true
  redis:
    password: ${REDIS_PASSWORD}
    cluster:
      nodes: ${REDIS_NODES}
    lettuce:
      pool:
        max-active: ${REDIS_POOL_MAX_ACTIVE}
        max-wait: ${REDIS_POOL_MAX_WAIT}
        max-idle: ${REDIS_POOL_MAX_IDLE}
        min-idle: ${REDIS_POOL_MIN_IDLE}
    timeout: 10000

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
        loggerLevel: basic

hestia:
  ribbon:
    listOfServers: ${HESTIA_URL}

heracles:
  ribbon:
    listOfServers: ${HERACLES_URL}

athena:
  ribbon:
    listOfServers: ${ATHENA_URL}

metis:
  ribbon:
    listOfServers: ${METIS_URL}

## MyBatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    localCacheScope: STATEMENT
  apollo:
    type-enums-package: com.criltds.provider.apollo.enums.*
    type-aliases-package: com.criltds.provider.apollo.db.rmdb.entity
    mapper-locations: classpath:com/criltds/provider/apollo/db/rmdb/mapper/*Mapper.xml

management:
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /internal/actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false

ares:
  ribbon:
    listOfServers: ${ARES_URL}
logging:
  level:
    com.criltds.provider.apollo.db.rmdb:
      mapper: debug